/**
 * The rule register (docs/rules.md, generated by scripts/rules.ts): it is
 * current, and every coded rule of the ledger has a place it is raised, a
 * design section that states it, and a test or a contract fixture that
 * exercises it. A change to a rule changes that file, so a pull request's
 * diff shows what the change reaches.
 */
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { buildRegister, gaps, REGISTER, registerMarkdown } from "../scripts/rules.ts";

test("docs/rules.md is what scripts/rules.ts generates from the code now", async () => {
  const now = registerMarkdown(buildRegister());
  const committed = await readFile(REGISTER, "utf8").catch(() => "");
  assert.ok(committed === now, "docs/rules.md is stale: run node --experimental-strip-types scripts/rules.ts --write and commit it");
});

test("every coded rule is raised somewhere, stated in the design, and exercised by a test or a contract fixture", () => {
  const rules = buildRegister();
  assert.ok(rules.length >= 30, `the register holds ${rules.length} rules`);
  assert.deepEqual(gaps(rules), []);
  for (const kind of ["defect", "warning", "cap"]) assert.ok(rules.some((r) => r.kind === kind), `no ${kind} in the register`);
});
