#!/usr/bin/env python3
"""Turn packs into an image recipe.

  recipe.py PROFILE --packs DIR --out DIR [--base IMAGE]

A profile is a named set of packs. For each pack, `requires/host.json` says
which binaries its method calls and how to install them, and
`requires/python.txt` lists the libraries its tools import. The packs are
the single source: the kickoff checks a host against them, and this turns
the same lines into an image.

Writes OUT/spec.json (what to install, and what cannot be installed from a
package manager) and OUT/Dockerfile, and copies install.py beside them, so
OUT is a complete build context:

  docker build -t dfirswarm-re:dev OUT
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

PROFILES = {
    "disk": ["computer-forensics-base", "encrypted-containers", "windows-forensics"],
    "memory": ["memory-forensics"],
    "re": ["reverse-engineering"],
    "network": ["network-forensics"],
    "linux": ["linux-forensics"],
    "mobile": ["mobile-forensics"],
}

APT = re.compile(r"^(?:sudo\s+)?apt(?:-get)?\s+install\s+(.+)$")
PIP = re.compile(r"^python3\s+-m\s+pip\s+install\s+(.+)$")


def words(tail: str) -> list[str]:
    return [w for w in tail.split() if not w.startswith("-")]


def read_pack(packs: Path, name: str) -> dict:
    spec = {"apt": {}, "pip": {}, "requirements": [], "binaries": [], "manual": []}
    host = packs / name / "requires" / "host.json"
    if host.exists():
        for b in json.loads(host.read_text())["binaries"]:
            line = (b.get("install") or {}).get("apt", "").strip()
            required = not b.get("optional", False)
            spec["binaries"].append({"name": b["name"], "pack": name, "required": required,
                                     "licence": b.get("licence")})
            if m := APT.match(line):
                for p in words(m.group(1)):
                    spec["apt"][p] = spec["apt"].get(p, False) or required
            elif m := PIP.match(line):
                for p in words(m.group(1)):
                    spec["pip"][p] = spec["pip"].get(p, False) or required
            else:
                spec["manual"].append({"name": b["name"], "pack": name, "how": line or "no install line"})
    reqs = packs / name / "requires" / "python.txt"
    if reqs.exists():
        for raw in reqs.read_text().splitlines():
            line = raw.split("#", 1)[0].strip()
            if line:
                spec["requirements"].append(line)
    return spec


def merge(specs: list[dict]) -> dict:
    out = {"apt": {}, "pip": {}, "requirements": [], "binaries": [], "manual": []}
    for s in specs:
        for kind in ("apt", "pip"):
            for p, req in s[kind].items():
                out[kind][p] = out[kind].get(p, False) or req
        out["requirements"] += [r for r in s["requirements"] if r not in out["requirements"]]
        out["binaries"] += s["binaries"]
        out["manual"] += s["manual"]
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("profile", choices=sorted(PROFILES))
    ap.add_argument("--packs", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--base", default="dfirswarm-base:dev")
    a = ap.parse_args()

    packs = PROFILES[a.profile]
    missing = [p for p in packs if not (a.packs / p).is_dir()]
    if missing:
        print(f"recipe: no such pack(s): {', '.join(missing)}", file=sys.stderr)
        return 2
    spec = merge([read_pack(a.packs, p) for p in packs])
    spec = {"profile": a.profile, "packs": packs, **spec}

    a.out.mkdir(parents=True, exist_ok=True)
    (a.out / "spec.json").write_text(json.dumps(spec, indent=1) + "\n")
    shutil.copy(Path(__file__).with_name("install.py"), a.out / "install.py")
    (a.out / "Dockerfile").write_text(f"""# Generated by recipe.py from packs: {", ".join(packs)}. Do not edit.
ARG BASE={a.base}
FROM ${{BASE}}
COPY install.py spec.json /tmp/dfirswarm-build/
RUN python3 /tmp/dfirswarm-build/install.py /tmp/dfirswarm-build/spec.json \\
 && rm -rf /tmp/dfirswarm-build
ENV PATH=/opt/dfir/venv/bin:$PATH
LABEL dev.dfirswarm.profile="{a.profile}" \\
      dev.dfirswarm.packs="{",".join(packs)}"
""")
    req_apt = sum(spec["apt"].values())
    print(f"{a.profile}: {len(spec['apt'])} apt ({req_apt} required), {len(spec['pip'])} pip, "
          f"{len(spec['requirements'])} python requirements, {len(spec['manual'])} not from a package manager")
    return 0


if __name__ == "__main__":
    sys.exit(main())
