#!/usr/bin/env node
/**
 * A certification template for a package (swarm.sh certify <package>): the
 * kind of written certification FRE 902(13) and 902(14) contemplate, by a
 * qualified person, that records were generated by a process that produces
 * an accurate result and that a copy is identified by a process of digital
 * identification. This fills in what the package itself says (its manifest's
 * sha256, who signed it, the custody verdict, every release of the report
 * and who sealed each, the redactions) and the verification steps that were
 * run with their output, verbatim; the certifying person's name,
 * qualification, statements and signature are left for that person. Nothing
 * in it is true because this tool printed it, and it is not legal advice:
 * counsel decides whether and how it is used, and adapts it to the
 * jurisdiction.
 *
 * A PDF is not signed inside (no PAdES): a release binds the PDF's sha256 in
 * release.json, whose detached ssh signature is the examiner's. A certifier
 * signs this file the same way (ssh-keygen -Y sign -n
 * dfirswarm-certification).
 *
 *   node scripts/certify.ts --package DIR --verify-output FILE --verify-exit N [--target PATH] [--allowed-signers FILE] [--tsa-ca FILE]
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { readReleases } from "./release-record.ts";

const sha256 = (b: string | Buffer) => createHash("sha256").update(b).digest("hex");

/** What each exit of swarm.sh verify means, in the certificate's words. */
export const VERIFY_EXITS: Record<number, string> = {
  0: "every file matches the manifest, the manifest's signature is valid and its signer is one the allowed-signers file names (and so is every adopting examiner's key)",
  3: "every file matches the manifest and the signature is sound, and who signed (or an adopting examiner's key) was not checked against a signer register",
  4: "every file matches the manifest, and the package is not signed",
  1: "SOMETHING DOES NOT HOLD: the output above names it",
  2: "the package could not be read",
};

export type CertifyInput = { pkg: string; target: string; verifyOutput: string; verifyExit: number; allowedSigners?: string; tsaCa?: string; at?: string };

export function certificationText(o: CertifyInput): string {
  const dir = resolve(o.pkg);
  const read = (rel: string) => (existsSync(join(dir, rel)) ? readFileSync(join(dir, rel), "utf8") : null);
  const manifest = read("MANIFEST.txt");
  const signer = read("SIGNER.txt");
  const field = (text: string | null, name: string) => new RegExp(`^${name} (.+)$`, "m").exec(text ?? "")?.[1] ?? null;
  let custody: { at?: string; summary?: string } | null = null;
  try {
    custody = read("custody.json") ? (JSON.parse(read("custody.json") as string) as { at?: string; summary?: string }) : null;
  } catch {
    custody = null;
  }
  let redactions: { entries?: unknown[]; changes?: unknown[]; leak_scan?: { hits?: unknown[] } } | null = null;
  try {
    redactions = read("REDACTIONS.json") ? JSON.parse(read("REDACTIONS.json") as string) : null;
  } catch {
    redactions = null;
  }
  const releases = readReleases(dir);
  const latest = releases.at(-1)?.record ?? null;
  const adopted = [...releases].reverse().find((r) => r.record?.state === "adopted") ?? null;
  const at = o.at ?? new Date().toISOString();
  const blank = "______________________________";
  const L: string[] = [];
  L.push(
    "CERTIFICATION OF RECORDS GENERATED BY AN ELECTRONIC PROCESS",
    "(a template, for a qualified person to complete and sign)",
    "",
    `Prepared by DFIR Swarm's swarm.sh certify at ${at} from the package at ${o.target}. It is of the kind`,
    "Federal Rules of Evidence 902(13) and 902(14) contemplate: a certification by a qualified person that",
    "records were generated by an electronic process or system that produces an accurate result, and that",
    "a copy was identified as a true copy by a process of digital identification. Everything below the",
    "certifier does not confirm is struck out. Nothing here is true because this tool printed it. This is",
    "not legal advice: counsel decides whether, and how, it is used, and adapts it to the jurisdiction.",
    "",
    "1. The person certifying",
    "",
    `   Name:                          ${blank}`,
    `   Title and organisation:        ${blank}`,
    `   Qualification (how I know the process that made these records, and the checks below):`,
    `                                  ${blank}`,
    "",
    "2. The records",
    "",
    `   Package:                       ${o.target}`,
    `   Its manifest:                  MANIFEST.txt, sha256 ${manifest ? sha256(manifest) : "NONE (not a package)"}, listing ${manifest ? manifest.split("\n").filter(Boolean).length : 0} file(s) by their SHA-256`,
    `   Signed:                        ${existsSync(join(dir, "MANIFEST.txt.sig")) ? `yes (MANIFEST.txt.sig): principal ${field(signer, "principal") ?? "?"}, key ${field(signer, "key") ?? "?"}, examiner ${field(signer, "examiner") ?? "not recorded"}, at ${field(signer, "signed_at") ?? "?"}` : "no"}`,
    `   Kind:                          ${(read("PACKAGE-KIND.txt") ?? "not said").trim()}`,
    `   Custody verdict:               ${custody ? `custody.json, sha256 ${sha256(read("custody.json") as string)}, taken ${custody.at ?? "?"} on the host after the run` : "none in the package"}`,
    `   Redacted:                      ${redactions ? `yes: ${redactions.entries?.length ?? 0} sensitive entr${(redactions.entries?.length ?? 0) === 1 ? "y" : "ies"}, ${redactions.changes?.length ?? 0} file(s) changed, each change in REDACTIONS.json; the scan after it: ${(redactions.leak_scan?.hits?.length ?? 0) ? `${redactions.leak_scan?.hits?.length} hit(s) listed` : "nothing found"}` : existsSync(join(dir, "REDACTIONS.txt")) ? "yes (REDACTIONS.txt; an older package: what each change replaced is not recorded)" : "no"}`,
    "",
    "   The report's releases (release/), each a signed record of which bytes were handed over:",
  );
  if (!releases.length) L.push("     none (a package from before releases, or a run whose custody was not taken)");
  for (const r of releases) {
    const x = r.record;
    if (!x) {
      L.push(`     v${r.version}: ${r.error ?? "unreadable"}`);
      continue;
    }
    L.push(
      `     v${r.version}: ${x.state === "adopted" ? `ADOPTED by ${x.signer.examiner?.name ?? "?"} (${x.signer.examiner?.organisation ?? "?"}), an enrolled examiner, key ${x.signer.fingerprint}` : `DRAFT, sealed by the install's machine key ${x.signer.fingerprint} (not an examiner; adopted by no one)`}, ${x.at}`,
      `         release.json sha256 ${r.sha256}; report.html sha256 ${x.report.html.sha256}${x.report.pdf ? `; report.pdf sha256 ${x.report.pdf.sha256} (bound here; the PDF carries no signature of its own)` : ""}; ${x.reason}`,
    );
  }
  L.push(
    "",
    "3. The statements (each confirmed, or struck, by the person certifying)",
    "",
    `   [ ] The records were generated by an electronic process or system, DFIR Swarm ${latest?.versions.dfirswarm ?? "(version not recorded)"}${latest?.versions.harness_commit_at_kickoff ? ` at commit ${latest.versions.harness_commit_at_kickoff}` : ""}, that produces an accurate`,
    `       result, as shown by: ${blank}`,
    "   [ ] The records were made at or near the time of the acts they record, by the process, in the course",
    "       of the examination, as a regular practice of that examination.",
    "   [ ] The copy delivered is identified as a true copy by a process of digital identification: each",
    "       file's SHA-256 in MANIFEST.txt, computed again by the steps below, matches.",
    `   [ ] ${adopted ? `The conclusions release v${adopted.version} lists as adopted or qualified are ${adopted.record?.signer.examiner?.name ?? "the examiner"}'s opinions; every other conclusion is the agents', not adopted.` : "No examiner adopted the report: every conclusion in it is the agents'."}`,
    "",
    "4. The verification steps run, and their output, verbatim",
    "",
    `   $ swarm.sh verify ${o.target}${o.allowedSigners ? ` --allowed-signers ${o.allowedSigners}` : ""}${o.tsaCa ? ` --tsa-ca ${o.tsaCa}` : ""}`,
    ...o.verifyOutput.replace(/\n+$/, "").split("\n").map((l) => `   ${l}`),
    `   exit ${o.verifyExit}: ${VERIFY_EXITS[o.verifyExit] ?? "an exit this template does not know"}`,
    "",
    "5. What these checks do not establish",
    "",
    "   - That any conclusion is correct. The checks show which bytes were handed over, who sealed each",
    "     release, and that nothing listed changed since; an adoption is the examiner's opinion.",
    "   - That the evidence copy equals the original acquisition, unless the custody verdict held it to",
    "     acquisition hashes given at kickoff.",
    "   - Who holds a key, beyond what the allowed-signers file given (the organisation's signer",
    "     register) says; without one, only that each signature is sound under the key its record names.",
    "   - Any time beyond the host's clock, unless a timestamp token was verified against the",
    "     authority's CA; a token obtained later dates the proof of existence from then.",
    "   - That the anchor files beside the run are beyond the reach of the operator's own account: an",
    "     independent copy (an object-locked bucket, a records custodian's archive) is what is.",
    "",
    "6. Declaration",
    "",
    `   I declare under penalty of perjury under the laws of ${blank} that the foregoing is true and`,
    "   correct. (Where 28 U.S.C. 1746 applies, this form; elsewhere, the form the jurisdiction asks for.)",
    "",
    `   Signature: ${blank}      Date: ${blank}`,
    `   Place:     ${blank}`,
    "",
    "   The person certifying may also sign this file itself, detached:",
    "     ssh-keygen -Y sign -f <their key> -n dfirswarm-certification certification.txt",
    "",
  );
  return `${L.join("\n")}`;
}

function opt(args: string[], name: string): string | undefined {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  const args = process.argv.slice(2);
  const pkg = opt(args, "--package");
  const output = opt(args, "--verify-output");
  if (!pkg || !output || opt(args, "--verify-exit") === undefined) {
    console.error("usage: certify.ts --package DIR --verify-output FILE --verify-exit N [--target PATH] [--allowed-signers FILE] [--tsa-ca FILE]");
    process.exit(2);
  }
  process.stdout.write(certificationText({ pkg, target: opt(args, "--target") ?? pkg, verifyOutput: readFileSync(output, "utf8"), verifyExit: Number(opt(args, "--verify-exit")), allowedSigners: opt(args, "--allowed-signers"), tsaCa: opt(args, "--tsa-ca") }));
}
